# Generated by Django 3.0.7 on 2023-08-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200, verbose_name='Titulo')),
                ('price', models.CharField(max_length=15, verbose_name='Precio')),
                ('image', models.ImageField(upload_to='cars', verbose_name='Imagen')),
                ('description', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('motor', models.CharField(max_length=100, verbose_name='Motor')),
                ('cilindraje', models.CharField(max_length=100, verbose_name='Cilindraje')),
                ('horsepower', models.CharField(max_length=100, verbose_name='Caballos De Fuerza')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
        ),
    ]
