# Generated by Django 3.0.7 on 2023-08-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='name'),
            preserve_default=False,
        ),
    ]
